class RuleEngine:
    """
    Forward-chaining rule engine.

    The engine starts with a set of facts, evaluates the rules,
    adds newly generated facts, and continues evaluating until
    no new facts can be produced.
    """

    def __init__(self, rules):
        self.rules = rules

    def run(self, facts):
        """
        Execute the rule engine.

        Parameters:
            facts (dict):
                Initial facts about an order/inventory state.

        Returns:
            tuple:
                (
                    final_facts,
                    fired_rules
                )
        """

        # Make a copy so the original dictionary is not modified.
        facts = facts.copy()

        fired_rules = []

        # Continue running while rules are producing new facts.
        changed = True

        while changed:
            changed = False

            for rule in self.rules:

                result = rule.evaluate(facts)

                # Rule did not fire.
                if result is None:
                    continue

                # Add the facts generated by the rule.
                for key, value in result.items():

                    # Only count it as a change if the value
                    # is actually new or different.
                    if facts.get(key) != value:
                        facts[key] = value
                        changed = True

                # Record the rule only once.
                if rule.name not in fired_rules:
                    fired_rules.append(rule.name)

        return facts, fired_rules